### ISSUE TITLE
Should QNode have a "name" field?

### ISSUE THREAD

**Issue by edeutsch** [NCATS-Tangerine/NCATS-ReasonerStdAPI#30]
At present, all query_graph nodes (QNode in the YAML) has only node_id (internal identifier like 'n00'), curie, and type. I can think of some cases where the user may have a name but not the curie. And the reasoner could be tasked with determining appropriate curies from the name (or confessing not to be able to do so).

Okay to add "name"?

What do you think?

**Comment by patrickkwang** [comment]
The SRI team provides a service to assist in name->curie resolution: http://robokop.renci.org:2434/docs

Due to the inherent ambiguity in natural language, this is best done by the client when formulating the query.

I propose to close this issue, keeping `curie` as the authoritative carrier of query node identification. +1 this comment to vote in favor, -1 against (and provide a counterargument).
