### ISSUE TITLE
Node Weights

### ISSUE THREAD

**Issue by srensi** [NCATS-Tangerine/NCATS-ReasonerStdAPI#56]
Can we have a weight field for node objects?  I am returning node weights in KG. 

Technically this could be done using "node attributes" field, but should it be a first class property?

Has there been any previous discussion of this?

**Comment by edeutsch** [comment]
There are already edge weights, but you're right no node weights. What sort of examples do you have that weight your nodes? Seems it would be difficult to provide universal weights for nodes.. seems like the importance of a node depends on the relationships relevant in a particular context.

**Comment by srensi** [comment]
I mainly use for purposes of display and interpretation.  I see problem with universality and am not necessarily married to the idea of externalizing weights.

**Comment by patrickkwang** [comment]
The spec prohibits very little: right now you could add a `weight` field to your nodes and everything should validate fine because `additionalProperties: true`. The only reason to add a `weight` field to the spec is to ensure that everyone uses it consistently (e.g. enforcing that the value is a float). Unless that field is included in the `required` list, there is no guarantee that a reasoner will use it rather than a `NodeAttribute`.

@edeutsch, we've begun running into the same sort of issue you describe while weighting edges; the informativeness of any edge depends on how it's used in a result. So we'd like to apply some kind of metadata instead to an edge _binding_, which the spec actually does not allow. Would a generalization of the result format be useful to other folks?

**Comment by edeutsch** [comment]
We certainly have a need to add additional semantic concepts to the nodes and edges in a query_graph (beyond is_set). It's not obvious to me that we need metadata on the bindings at this point. But maybe we just haven't stumbled into that yet. It would be a pretty big change.

**Comment by patrickkwang** [comment]
1c0a805d5e3b3e4e8d339ef1db14cfe336d2de0d solves the problem @edeutsch and I were discussing. But was @srensi's original question answered?
