### ISSUE TITLE
Schema version numbering?

### ISSUE THREAD

**Issue by edeutsch** [NCATS-Tangerine/NCATS-ReasonerStdAPI#88]
Should we try to be a bit more fastidious about the schema version numbering? 

Right now the schema version in both files shows 0.9.2. But it's different than what we tagged as 0.9.2. Maybe we could just update the two files to 0.9.3? 

Or is there some more elegant want to set the version number in the files to connote that this is an interim state between the tagged 0.9.2 and whatever the next tag is?

**Comment by patrickkwang** [comment]
Github projects typically handle versioning in one of two ways:

1) Don't worry about the version numbers until you make a release. You can see this [here](https://github.com/python/cpython/tree/3.8), where they have made commits to the 3.8 branch since 3.8.0b4, but will update all the documentation just before an official release is made.
2) Make all incremental pull requests to a devel branch and make sure version numbers are updated before pulling it into master. That way the master branch is always at the latest official release.

Option 1 is much more popular these days, so I think we're doing things the right way.

**Comment by edeutsch** [comment]
Option 2 seems a lot tidier to me, but if no one else objects to our use of option 1, then I'm okay.

**Comment by southalln** [comment]
Thanks for the excellent conversation on the call. I don't think 1 and 2 are mutually exclusive. I think it should be assumed that whatever users pull from the default branch (which is currently Master) should be the current "production" release of the standard and not what is in development.   For those uninitiated to the inner-workings of this project, their naive assumption will not generally get them into trouble. I like the idea, then, of tagging the version number as the last commit before merging with Master, and immediately tagging a new version 'number', e.g. "0.9.3+dev" as the next commit into the active dev branch. Using tags as well for each "production" release seems redundant but also good practice nonetheless. ... So ... that's a long-winded endorsement of doing both 1 and 2?

**Comment by patrickkwang** [comment]
What is the purpose of tagging a "+dev" version for the first post-release commit in the dev branch? Each tag/release points at one specific state of the repository, and I'm not sure why someone would need to get back to _that_ specific state.

My stance is that `git pull` should never be the way someone tries to get a working version. Most people who want to _use_ a thing don't care about the development history. Releases are GitHub's mechanism for distributing stable software/documents, and I think we should use them. We can make the distinction between the master branch and the latest stable release very prominent by putting a link to the releases at the top of the README.

**Comment by edeutsch** [comment]
I thought I heard on the call last week (from Noel?) suggestion that the `master` branch should reflect the latest release since that's what naive visitors would expect. This seems sensible to me.

So I suggest:
`master` branch contains the current release version, with an embedded version number that is an even final number (e.g. 0.9.2)
`development` branch contains changes in progress, with an embedded version number that is the next odd number over release with 'dev' appended. (e.g. 0.9.3dev) (unless it is synchronized with `master`
`extended` branch contains additional properties that are used and promoted by at least one team, with an embedded version number that is the next odd number over release with 'ext' appended. (e.g. 0.9.3ext), unless `development` is synchronized with `master`, in which case it is the release version with 'ext' appended. (e.g. 0.9.2ext).

I'll make it a pull request.

**Comment by edeutsch** [comment]
> What is the purpose of tagging a "+dev" version for the first post-release commit in the dev branch?

The purpose in my view is to have a formal name by which to call it from *outside* the repo.
I would like to express "This JSON document that you are currently reading conforms most closely to version X of the spec". I would like to express that I am implementing "0.9.3dev" and that there's a difference between that and the release version "0.9.2"

**Comment by patrickkwang** [comment]
Okay, that makes sense. I see three alternatives:
1. We can tag any arbitrary pre-release version with e.g. 0.9.2-dev.3 as necessary. See [Semantic Versioning](https://semver.org/#spec-item-9) (9 and 10) for the syntax for these.
2. If brevity is not critical, you can always just refer to a version by its commit ID without touching the repo.
3. We can increase the frequency of releases. As long as the master branch is in a stable state and no breaking changes have been made since the last minor version, there's no problem releasing a patch. Note this is a post-1.0 protocol, not how we've been managing things to date. As long as pull requests are properly approved, it should not be a big governance headache to tag master as a new patch.

**Comment by edeutsch** [comment]
I don't like option 2 because I think it should be instantly human recognizable what version is being referenced
I don't think we can manage option 3 given historical precedent. I think we would like to minimize the number of different versions and therefore pile various changes into one release and given our past history I think there should just be a period of development between releases.

I like option 1. It is what I was imagining.
But I'll again promote the idea that we have in intermediate number as well. Because I find 0.9.2-dev.3 versus the release '0.9.2' ambiguous. Is this development leading up to release 0.9.2? or is it development past release 0.9.2? It's unclear. If we use '0.9.3-dev' for what we're doing now, it is unambiguously clear that this has moved past 0.9.2. When we're done fooling around with 0.9.3-dev, we tag it 0.9.4. No ambiguity.

**Comment by patrickkwang** [comment]
0.9.2-dev.3 is meant to precede 0.9.2: https://semver.org/#spec-item-11

**Comment by edeutsch** [comment]
maybe. but why implement it in a way that requires being in the know or consulting the documentation to know which, when you could just implement it in a way that leaves no room for confusion?

**Comment by patrickkwang** [comment]
#116
